name: 'My Custom Chart Action'
description: 'A custom action that gets data and draws a chart'
inputs:
  myInput:
    description: 'Organization name'
    required: true
outputs:
  myOutput:
    description: 'An example output'
runs:
  using: 'node14'
  main: 'index.mjs'
