name: Custom Chart Action Workflow
on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version here
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Run custom chart action
      uses: ./
      with:
        myInput: 'TickLabVN'

    - name: Commit and push changes
      run: |
          git pull
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          git add .
          git commit -m "Update chart data"
          git push
